notifications:
  email: false

sudo: true

language: python

cache:
  - pip

python:
  - 2.7

services:
  - docker

before_install:
  - travis_retry pip install yadage

script:
  - yadage-validate workflow/yadage/workflow.yaml | grep -q 'workflow validates'
  - rm -rf results && mkdir results
  - docker run -i -t  --rm -v `pwd`/code:/code -v `pwd`/data:/data -v `pwd`/results:/results python:2.7 python /code/helloworld.py --sleeptime 0
  - grep -q 'Hello Joe Bloggs!' results/greetings.txt
