metadata:
  author: "REANA Developers."
  title: "Helloworld REANA demo in CWL"
environment:
  - type: docker
    image: python:2.7
workflow:
  type: cwl
  file: helloworld.cwl
parameters:
  input: helloworld-job.yml
